const fs = require('fs');
const path = require('path');

// Existing movies from src/movies.js
const existingMovies = require('../src/movies');

// 35 New Blockbusters to expand the catalog to 50 titles!
const newMovies = [
  {
    id: "rrr",
    title: "RRR",
    type: "Movie",
    overview: "A fearless warrior on a perilous mission comes face to face with a steely cop serving British forces in pre-independent India in an explosive tale of brotherhood and rebellion.",
    backdrop: "https://image.tmdb.org/t/p/w1280/u0x6ooft3N8w5sZ2u53Z4b8oK0e.jpg",
    poster: "https://image.tmdb.org/t/p/w780/wE0noFUq1q79wGZ7pB7g15xH86b.jpg",
    matchScore: 99,
    year: "2022",
    ageRating: "U/A 16+",
    duration: "3h 7m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Historical Drama", "Rebellion Epic"],
    cast: ["N.T. Rama Rao Jr.", "Ram Charan", "Alia Bhatt", "Ajay Devgn"],
    creator: "S. S. Rajamouli",
    category: "trending",
    isOriginal: false,
    top10Rank: 2,
    tmdbId: 579974,
    youtubeTrailerId: "NgBoMJy386M"
  },
  {
    id: "leo",
    title: "Leo: Bloody Sweet",
    type: "Movie",
    overview: "A mild-mannered cafe owner in Himachal Pradesh gets pulled into a violent underworld when ruthless mobsters suspect he is a legendary gangster from their bloody past.",
    backdrop: "https://image.tmdb.org/t/p/w1280/k1gZ2NfZ5w6m5Qv8s8k6D2Z8y2.jpg",
    poster: "https://image.tmdb.org/t/p/w780/pD6sL4vntUOXHmuvJPPZAgUJqq9.jpg",
    matchScore: 97,
    year: "2023",
    ageRating: "A 18+",
    duration: "2h 44m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Crime Thriller", "Gangster"],
    cast: ["Thalapathy Vijay", "Sanjay Dutt", "Trisha Krishnan", "Arjun Sarja"],
    creator: "Lokesh Kanagaraj",
    category: "trending",
    isOriginal: false,
    top10Rank: 3,
    tmdbId: 1075794,
    youtubeTrailerId: "Po3jStA673E"
  },
  {
    id: "jawan",
    title: "Jawan",
    type: "Movie",
    overview: "A high-octane emotional journey of a prison officer who rectifies the wrongs in society with a team of six women inmates who take on corrupt politicians and arms dealers.",
    backdrop: "https://image.tmdb.org/t/p/w1280/jXJxMcVoTTg5upA505z2U29rUIn.jpg",
    poster: "https://image.tmdb.org/t/p/w780/jYW80UvA4bH2Qv9G7mQ5vB5L1k.jpg",
    matchScore: 98,
    year: "2023",
    ageRating: "U/A 16+",
    duration: "2h 49m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Vigilante Thriller", "Masala Drama"],
    cast: ["Shah Rukh Khan", "Nayanthara", "Vijay Sethupathi", "Deepika Padukone"],
    creator: "Atlee",
    category: "trending",
    isOriginal: false,
    top10Rank: 4,
    tmdbId: 872906,
    youtubeTrailerId: "MWOlnZSnXWE"
  },
  {
    id: "animal",
    title: "Animal",
    type: "Movie",
    overview: "A son's obsessive love for his distant industrialist father drives him to unleash an unprecedented wave of brutal violence when his father is targeted in an assassination attempt.",
    backdrop: "https://image.tmdb.org/t/p/w1280/b6P2pY0r5g3gqJ9Y0r5g3gqJ9Y.jpg",
    poster: "https://image.tmdb.org/t/p/w780/hr9rjR4JOpEi2tpT4XNuuuQISG3.jpg",
    matchScore: 96,
    year: "2023",
    ageRating: "A 18+",
    duration: "3h 24m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Crime Drama", "Psychological Thriller"],
    cast: ["Ranbir Kapoor", "Anil Kapoor", "Bobby Deol", "Rashmika Mandanna"],
    creator: "Sandeep Reddy Vanga",
    category: "trending",
    isOriginal: false,
    top10Rank: 5,
    tmdbId: 781732,
    youtubeTrailerId: "Dydmpfo68DA"
  },
  {
    id: "kalki-2898-ad",
    title: "Kalki 2898 AD",
    type: "Movie",
    overview: "Set in a dystopian post-apocalyptic future in the desert city of Kasi, an ancient warrior awakens from deep slumber to protect the avatar destined to restore cosmic order.",
    backdrop: "https://image.tmdb.org/t/p/w1280/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    poster: "https://image.tmdb.org/t/p/w780/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
    matchScore: 98,
    year: "2024",
    ageRating: "U/A 13+",
    duration: "3h 1m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Sci-Fi", "Mythological Epic", "Action"],
    cast: ["Prabhas", "Amitabh Bachchan", "Kamal Haasan", "Deepika Padukone"],
    creator: "Nag Ashwin",
    category: "trending",
    isOriginal: false,
    top10Rank: 6,
    tmdbId: 1022789,
    youtubeTrailerId: "y1-w1pUGuz4"
  },
  {
    id: "kgf-chapter-2",
    title: "K.G.F: Chapter 2",
    type: "Movie",
    overview: "Rocky now commands the blood-soaked Kolar Gold Fields, but bloodthirsty enemies, including the brutal Adheera and prime minister Ramika Sen, emerge to take back control.",
    backdrop: "https://image.tmdb.org/t/p/w1280/4Qp1b5Wk100Q2w3e4r5t6y7u8.jpg",
    poster: "https://image.tmdb.org/t/p/w780/67107127e1b5Wk100Q2w3e4r5.jpg",
    matchScore: 97,
    year: "2022",
    ageRating: "U/A 16+",
    duration: "2h 48m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Period Gangster", "Drama"],
    cast: ["Yash", "Sanjay Dutt", "Raveena Tandon", "Srinidhi Shetty"],
    creator: "Prashanth Neel",
    category: "action",
    isOriginal: false,
    top10Rank: 7,
    tmdbId: 588228,
    youtubeTrailerId: "JKa05nyUmuQ"
  },
  {
    id: "salaar",
    title: "Salaar: Part 1 – Ceasefire",
    type: "Movie",
    overview: "A hardened gang leader pledges to uphold a sacred promise made to his dying childhood friend by taking on rival criminal empires in the dystopian sovereign city of Khansaar.",
    backdrop: "https://image.tmdb.org/t/p/w1280/m9fEa2WlD1p2o3i4u5y6t7r8.jpg",
    poster: "https://image.tmdb.org/t/p/w780/75bXfG0W9k8j7h6g5f4d3s2a1.jpg",
    matchScore: 96,
    year: "2023",
    ageRating: "A 18+",
    duration: "2h 55m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Crime Drama", "Dystopian Thriller"],
    cast: ["Prabhas", "Prithviraj Sukumaran", "Shruti Haasan", "Jagapathi Babu"],
    creator: "Prashanth Neel",
    category: "action",
    isOriginal: false,
    top10Rank: 8,
    tmdbId: 897087,
    youtubeTrailerId: "4GPvYMKtrtI"
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    type: "Movie",
    overview: "The gripping story of American theoretical physicist J. Robert Oppenheimer and his role in the secretive Manhattan Project that developed the world's first nuclear weapons.",
    backdrop: "https://image.tmdb.org/t/p/w1280/fm6K9vYqq09939zwJu2cT9L7.jpg",
    poster: "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    matchScore: 99,
    year: "2023",
    ageRating: "R 16+",
    duration: "3h 0m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Biography", "Historical Drama", "Suspense"],
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    creator: "Christopher Nolan",
    category: "drama",
    isOriginal: false,
    top10Rank: 9,
    tmdbId: 872585,
    youtubeTrailerId: "uYPbbksJxIg"
  },
  {
    id: "dark",
    title: "Dark",
    type: "TV Series",
    overview: "A missing child sets four intertwined families on a frantic search for answers as they unearth a mind-bending time travel mystery that spans across four generations in Winden.",
    backdrop: "https://image.tmdb.org/t/p/w1280/3lBDg3i6nn5R2NKICJ797Urpy5a.jpg",
    poster: "https://image.tmdb.org/t/p/w780/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    matchScore: 99,
    year: "2020",
    ageRating: "U/A 16+",
    duration: "3 Seasons",
    quality: "4K Ultra HD",
    audio: "5.1 German/English",
    genres: ["Sci-Fi", "Time Travel", "Mystery", "Supernatural Thriller"],
    cast: ["Louis Hofmann", "Oliver Masucci", "Jördis Triebel"],
    creator: "Baran bo Odar",
    category: "scifi",
    isOriginal: true,
    top10Rank: 10,
    tmdbId: 70523,
    youtubeTrailerId: "rrwycJ08PSA"
  },
  {
    id: "narcos",
    title: "Narcos",
    type: "TV Series",
    overview: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar and the DEA agents working relentlessly to bring down the Medellin cartel.",
    backdrop: "https://image.tmdb.org/t/p/w1280/gL4UqXv9W7k01Z2s3d4e5f6g7.jpg",
    poster: "https://image.tmdb.org/t/p/w780/rTmal9fVEwh5x9hJ2v7o3u7X7s0.jpg",
    matchScore: 98,
    year: "2017",
    ageRating: "A 18+",
    duration: "3 Seasons",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Crime", "Biography", "Action Thriller"],
    cast: ["Wagner Moura", "Pedro Pascal", "Boyd Holbrook"],
    creator: "Chris Brancato",
    category: "drama",
    isOriginal: true,
    tmdbId: 63351,
    youtubeTrailerId: "xl8hmgMNCBo"
  },
  {
    id: "game-of-thrones",
    title: "Game of Thrones",
    type: "TV Series",
    overview: "Nine noble houses fight for dominion over the Seven Kingdoms of Westeros, while an ancient white walker threat awakens in the far north after being dormant for thousands of years.",
    backdrop: "https://image.tmdb.org/t/p/w1280/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    poster: "https://image.tmdb.org/t/p/w780/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    matchScore: 97,
    year: "2019",
    ageRating: "A 18+",
    duration: "8 Seasons",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Fantasy", "Drama", "Medieval War Epic"],
    cast: ["Emilia Clarke", "Kit Harington", "Peter Dinklage", "Lena Headey"],
    creator: "David Benioff & D.B. Weiss",
    category: "drama",
    isOriginal: false,
    tmdbId: 1399,
    youtubeTrailerId: "KPLWWIOCOOQ"
  },
  {
    id: "better-call-saul",
    title: "Better Call Saul",
    type: "TV Series",
    overview: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman in Albuquerque.",
    backdrop: "https://image.tmdb.org/t/p/w1280/hPea3Qy5Gd6Og4L2Vo6W9uP8z4J.jpg",
    poster: "https://image.tmdb.org/t/p/w780/fC2HDm5t0kHj7mTm73e2g6p2.jpg",
    matchScore: 99,
    year: "2022",
    ageRating: "U/A 16+",
    duration: "6 Seasons",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Crime", "Legal Drama", "Dark Comedy"],
    cast: ["Bob Odenkirk", "Rhea Seehorn", "Jonathan Banks", "Giancarlo Esposito"],
    creator: "Vince Gilligan & Peter Gould",
    category: "drama",
    isOriginal: true,
    tmdbId: 60059,
    youtubeTrailerId: "HN4oydykJFc"
  },
  {
    id: "the-batman",
    title: "The Batman",
    type: "Movie",
    overview: "When a sadistic serial killer known as the Riddler murders political figures in Gotham, the vigilante Batman is forced to plunge deep into the city's hidden criminal underworld.",
    backdrop: "https://image.tmdb.org/t/p/w1280/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    poster: "https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    matchScore: 96,
    year: "2022",
    ageRating: "U/A 16+",
    duration: "2h 56m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Neo-Noir", "Crime Detective"],
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Colin Farrell"],
    creator: "Matt Reeves",
    category: "action",
    isOriginal: false,
    tmdbId: 414906,
    youtubeTrailerId: "mqqft2x_Aa4"
  },
  {
    id: "fight-club",
    title: "Fight Club",
    type: "Movie",
    overview: "A depressed, insomniac office worker seeking an escape from his consumerist existence meets an enigmatic soap salesman and together they establish an underground fight club.",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    poster: "https://image.tmdb.org/t/p/w780/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    matchScore: 98,
    year: "1999",
    ageRating: "A 18+",
    duration: "2h 19m",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Psychological Thriller", "Cult Classic", "Dark Drama"],
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    creator: "David Fincher",
    category: "drama",
    isOriginal: false,
    tmdbId: 550,
    youtubeTrailerId: "qtRKdVHc-cE"
  },
  {
    id: "pulp-fiction",
    title: "Pulp Fiction",
    type: "Movie",
    overview: "The lives of two philosophizing mob hitmen, a stylish boxer, a crime boss and his unpredictable wife intersect in four wildly entertaining and violent tales of Los Angeles.",
    backdrop: "https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    poster: "https://image.tmdb.org/t/p/w780/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    matchScore: 99,
    year: "1994",
    ageRating: "A 18+",
    duration: "2h 34m",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Crime", "Dark Comedy", "Cult Classic"],
    cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"],
    creator: "Quentin Tarantino",
    category: "drama",
    isOriginal: false,
    tmdbId: 680,
    youtubeTrailerId: "s7EdQ4FqbhY"
  },
  {
    id: "the-matrix",
    title: "The Matrix",
    type: "Movie",
    overview: "When a hacker named Neo is contacted by mysterious rebel Morpheus, he awakens to discover humanity is trapped in a simulated reality engineered by sentient machines.",
    backdrop: "https://image.tmdb.org/t/p/w1280/l4QHerTSbMI7qgvej42P9FzD3Ac.jpg",
    poster: "https://image.tmdb.org/t/p/w780/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    matchScore: 99,
    year: "1999",
    ageRating: "U/A 16+",
    duration: "2h 16m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Sci-Fi", "Cyberpunk", "Action Martial Arts"],
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    creator: "The Wachowskis",
    category: "scifi",
    isOriginal: false,
    tmdbId: 603,
    youtubeTrailerId: "vKQi3bBA1y8"
  },
  {
    id: "avatar-way-of-water",
    title: "Avatar: The Way of Water",
    type: "Movie",
    overview: "Jake Sully and Ney'tiri have formed a family on Pandora. But when an old threat returns to conquer their world, they must flee to the oceanic Metkayina clan.",
    backdrop: "https://image.tmdb.org/t/p/w1280/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    poster: "https://image.tmdb.org/t/p/w780/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    matchScore: 97,
    year: "2022",
    ageRating: "U/A 13+",
    duration: "3h 12m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Sci-Fi", "Visual Masterpiece", "Adventure Fantasy"],
    cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Kate Winslet"],
    creator: "James Cameron",
    category: "scifi",
    isOriginal: false,
    tmdbId: 76600,
    youtubeTrailerId: "d9MyW72ELq0"
  },
  {
    id: "spider-man-spider-verse",
    title: "Spider-Man: Across the Spider-Verse",
    type: "Movie",
    overview: "Miles Morales catapults across the Multiverse, joining forces with Gwen Stacy and an elite Spider-Society tasked with preventing timeline collapse.",
    backdrop: "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    poster: "https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    matchScore: 99,
    year: "2023",
    ageRating: "U/A 13+",
    duration: "2h 20m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Animation", "Multiverse Sci-Fi", "Superhero Action"],
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac", "Daniel Kaluuya"],
    creator: "Joaquim Dos Santos & Kemp Powers",
    category: "action",
    isOriginal: false,
    tmdbId: 569094,
    youtubeTrailerId: "cqGjhVJWtEg"
  },
  {
    id: "gladiator",
    title: "Gladiator",
    type: "Movie",
    overview: "A betrayed Roman general Maximus Decimus Meridius is enslaved and trained as a gladiator, fighting his way to the Colosseum to avenge his slaughtered family.",
    backdrop: "https://image.tmdb.org/t/p/w1280/ArWn6HUv674z9Xm48RkO9k5f2Q.jpg",
    poster: "https://image.tmdb.org/t/p/w780/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    matchScore: 98,
    year: "2000",
    ageRating: "A 18+",
    duration: "2h 35m",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Action", "Historical Epic", "Revenge Drama"],
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
    creator: "Ridley Scott",
    category: "action",
    isOriginal: false,
    tmdbId: 98,
    youtubeTrailerId: "owK1qxDselE"
  },
  {
    id: "top-gun-maverick",
    title: "Top Gun: Maverick",
    type: "Movie",
    overview: "Pete 'Maverick' Mitchell returns to train a detachment of TOPGUN graduates for an impossible strike mission deep inside enemy territory.",
    backdrop: "https://image.tmdb.org/t/p/w1280/odJ4hx6g6vBt4lBWKFD1tGLILBW.jpg",
    poster: "https://image.tmdb.org/t/p/w780/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    matchScore: 99,
    year: "2022",
    ageRating: "U/A 13+",
    duration: "2h 10m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Aviation Thriller", "Adrenaline"],
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm"],
    creator: "Joseph Kosinski",
    category: "action",
    isOriginal: false,
    tmdbId: 361743,
    youtubeTrailerId: "giXco2jaZ_4"
  },
  {
    id: "avengers-endgame",
    title: "Avengers: Endgame",
    type: "Movie",
    overview: "After the devastating cosmic snap by Thanos wipes out half of all life, the surviving Avengers assemble to travel through time and undo the catastrophe.",
    backdrop: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    poster: "https://image.tmdb.org/t/p/w780/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    matchScore: 98,
    year: "2019",
    ageRating: "U/A 13+",
    duration: "3h 1m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Superhero Epic", "Sci-Fi Fantasy"],
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    creator: "Anthony & Joe Russo",
    category: "action",
    isOriginal: false,
    tmdbId: 299534,
    youtubeTrailerId: "TcMBFSGVi1c"
  },
  {
    id: "titanic",
    title: "Titanic",
    type: "Movie",
    overview: "A timeless romance blossoms between wealthy young rose and free-spirited artist Jack Dawson aboard the ill-fated maiden voyage of the unsinkable ship.",
    backdrop: "https://image.tmdb.org/t/p/w1280/yDIv5nDABnNsmGh978CrX3BglR5.jpg",
    poster: "https://image.tmdb.org/t/p/w780/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    matchScore: 98,
    year: "1997",
    ageRating: "U/A 16+",
    duration: "3h 14m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Romance", "Historical Drama", "Disaster Classic"],
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"],
    creator: "James Cameron",
    category: "drama",
    isOriginal: false,
    tmdbId: 597,
    youtubeTrailerId: "kVrqfYjkTdQ"
  },
  {
    id: "baahubali-2",
    title: "Baahubali 2: The Conclusion",
    type: "Movie",
    overview: "When Shiva learns of his royal lineage as Mahendra Baahubali, he sets out to overthrow the tyrannical ruler Bhallaladeva who murdered his noble father.",
    backdrop: "https://image.tmdb.org/t/p/w1280/q7fWnsG8Rk8q0Q1Q9n2y8x8q5e4.jpg",
    poster: "https://image.tmdb.org/t/p/w780/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    matchScore: 99,
    year: "2017",
    ageRating: "U/A 16+",
    duration: "2h 47m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Mythological Epic", "Historical Drama"],
    cast: ["Prabhas", "Rana Daggubati", "Anushka Shetty", "Tamannaah"],
    creator: "S. S. Rajamouli",
    category: "action",
    isOriginal: false,
    tmdbId: 350312,
    youtubeTrailerId: "G62HrubdD6o"
  },
  {
    id: "dangal",
    title: "Dangal",
    type: "Movie",
    overview: "Former amateur wrestler Mahavir Singh Phogat coaches his young daughters Geeta and Babita to become world-class wrestling champions against all societal odds.",
    backdrop: "https://image.tmdb.org/t/p/w1280/5F6D9F8e1b5Wk100Q2w3e4r5.jpg",
    poster: "https://image.tmdb.org/t/p/w780/pD6sL4vntUOXHmuvJPPZAgUJqq9.jpg",
    matchScore: 99,
    year: "2016",
    ageRating: "U/A",
    duration: "2h 41m",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Biography", "Sports Drama", "Inspirational"],
    cast: ["Aamir Khan", "Fatima Sana Shaikh", "Sanya Malhotra"],
    creator: "Nitesh Tiwari",
    category: "drama",
    isOriginal: false,
    tmdbId: 360814,
    youtubeTrailerId: "x_7YlGv9u1g"
  },
  {
    id: "three-idiots",
    title: "3 Idiots",
    type: "Movie",
    overview: "Two engineering graduates embark on a road trip across India to locate their brilliant, non-conformist friend Rancho who challenged the rigid education system.",
    backdrop: "https://image.tmdb.org/t/p/w1280/6xKzbqqll8q90Q1Q9n2y8x8q5e4.jpg",
    poster: "https://image.tmdb.org/t/p/w780/67107127e1b5Wk100Q2w3e4r5.jpg",
    matchScore: 99,
    year: "2009",
    ageRating: "U/A",
    duration: "2h 50m",
    quality: "1080p Full HD",
    audio: "5.1 Surround",
    genres: ["Comedy", "Inspirational Drama", "Coming-of-Age"],
    cast: ["Aamir Khan", "R. Madhavan", "Sharman Joshi", "Kareena Kapoor"],
    creator: "Rajkumar Hirani",
    category: "drama",
    isOriginal: false,
    tmdbId: 20453,
    youtubeTrailerId: "K0eDlFX9GMc"
  },
  {
    id: "vikram",
    title: "Vikram",
    type: "Movie",
    overview: "A black-ops squad leader investigates a string of vigilante assassinations of high-ranking police officials, uncovering a sprawling drug syndicate conspiracy.",
    backdrop: "https://image.tmdb.org/t/p/w1280/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    poster: "https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    matchScore: 97,
    year: "2022",
    ageRating: "A 18+",
    duration: "2h 54m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Neo-Noir", "Crime Thriller"],
    cast: ["Kamal Haasan", "Vijay Sethupathi", "Fahadh Faasil", "Suriya"],
    creator: "Lokesh Kanagaraj",
    category: "action",
    isOriginal: false,
    tmdbId: 757837,
    youtubeTrailerId: "OKBMCLzuvTW"
  },
  {
    id: "kantara",
    title: "Kantara",
    type: "Movie",
    overview: "In a coastal village bordered by ancient sacred forests, a rebellious youth must embrace the spiritual deity of his ancestors when a greedy landlord claims the holy land.",
    backdrop: "https://image.tmdb.org/t/p/w1280/hPea3Qy5Gd6Og4L2Vo6W9uP8z4J.jpg",
    poster: "https://image.tmdb.org/t/p/w780/fC2HDm5t0kHj7mTm73e2g6p2.jpg",
    matchScore: 98,
    year: "2022",
    ageRating: "U/A 16+",
    duration: "2h 28m",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Action", "Folklore Drama", "Supernatural Mystery"],
    cast: ["Rishab Shetty", "Sapthami Gowda", "Kishore"],
    creator: "Rishab Shetty",
    category: "drama",
    isOriginal: false,
    tmdbId: 1024546,
    youtubeTrailerId: "8Mrp_10vWdg"
  },
  {
    id: "pushpa-the-rise",
    title: "Pushpa: The Rise",
    type: "Movie",
    overview: "A fiery red sandalwood laborer in Andhra Pradesh rises to the top of an international smuggling syndicate, facing off against ruthless cops and rival crime bosses.",
    backdrop: "https://image.tmdb.org/t/p/w1280/4Qp1b5Wk100Q2w3e4r5t6y7u8.jpg",
    poster: "https://image.tmdb.org/t/p/w780/67107127e1b5Wk100Q2w3e4r5.jpg",
    matchScore: 96,
    year: "2021",
    ageRating: "U/A 16+",
    duration: "2h 59m",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Action", "Crime Thriller", "Gangster"],
    cast: ["Allu Arjun", "Rashmika Mandanna", "Fahadh Faasil"],
    creator: "Sukumar",
    category: "action",
    isOriginal: false,
    tmdbId: 693134,
    youtubeTrailerId: "Q1NKMPhP8PY"
  },
  {
    id: "attack-on-titan",
    title: "Attack on Titan",
    type: "TV Series",
    overview: "When colossal man-eating Titans breach the outermost protective wall, Eren Jaeger enlists in the elite Scout Regiment to fight back and uncover the true origin of their world.",
    backdrop: "https://image.tmdb.org/t/p/w1280/8tAB9vj4v96fS4a4a1w5y7e8.jpg",
    poster: "https://image.tmdb.org/t/p/w780/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    matchScore: 99,
    year: "2023",
    ageRating: "A 18+",
    duration: "4 Seasons",
    quality: "1080p Full HD",
    audio: "Japanese & English Dub",
    genres: ["Anime", "Dark Fantasy", "Military Sci-Fi"],
    cast: ["Yuki Kaji", "Yui Ishikawa", "Marina Inoue", "Hiroshi Kamiya"],
    creator: "Hajime Isayama",
    category: "scifi",
    isOriginal: false,
    tmdbId: 1429,
    youtubeTrailerId: "MGRm4IzK1SQ"
  },
  {
    id: "death-note",
    title: "Death Note",
    type: "TV Series",
    overview: "High school prodigy Light Yagami finds a supernatural notebook that kills anyone whose name is written in it, igniting an intense game of cat-and-mouse with master detective L.",
    backdrop: "https://image.tmdb.org/t/p/w1280/iKp91h0fQ5fF2A9o8g7w5y4.jpg",
    poster: "https://image.tmdb.org/t/p/w780/tCZFjgkdRLjsnb1mWC0h7j7rZ8.jpg",
    matchScore: 99,
    year: "2007",
    ageRating: "U/A 16+",
    duration: "1 Season",
    quality: "1080p Full HD",
    audio: "Japanese & English Dub",
    genres: ["Anime", "Psychological Thriller", "Supernatural Mystery"],
    cast: ["Mamoru Miyano", "Kappei Yamaguchi", "Brad Swaile"],
    creator: "Tsugumi Ohba",
    category: "drama",
    isOriginal: false,
    tmdbId: 13916,
    youtubeTrailerId: "NlJZ-YgAt-c"
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer: Kimetsu no Yaiba",
    type: "TV Series",
    overview: "After demons slaughter his family and infect his sister Nezuko, Tanjiro Kamado trains to become a Demon Slayer to save his sister and defeat the demonic king Muzan.",
    backdrop: "https://image.tmdb.org/t/p/w1280/3GQk6F8fP3f3A5o9g7w5y4.jpg",
    poster: "https://image.tmdb.org/t/p/w780/xUfRZu2mi8jH69hmV1fbu37x9qd.jpg",
    matchScore: 98,
    year: "2024",
    ageRating: "U/A 16+",
    duration: "4 Seasons",
    quality: "4K Ultra HD",
    audio: "Japanese & Hindi Dub",
    genres: ["Anime", "Action Fantasy", "Supernatural Martial Arts"],
    cast: ["Natsuki Hanae", "Akari Kito", "Hiro Shimono"],
    creator: "Koyoharu Gotouge",
    category: "action",
    isOriginal: false,
    tmdbId: 85937,
    youtubeTrailerId: "VQGCKyvzIM4"
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    type: "TV Series",
    overview: "Yuji Itadori swallows the cursed finger of Ryomen Sukuna and is initiated into Tokyo Jujutsu High to battle deadly curses threatening humankind.",
    backdrop: "https://image.tmdb.org/t/p/w1280/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    poster: "https://image.tmdb.org/t/p/w780/fUWtM8p3FfA5o9g7w5y4.jpg",
    matchScore: 98,
    year: "2023",
    ageRating: "U/A 16+",
    duration: "2 Seasons",
    quality: "1080p Full HD",
    audio: "Japanese & English Dub",
    genres: ["Anime", "Supernatural Action", "Dark Fantasy"],
    cast: ["Junya Enoki", "Yuma Uchida", "Asami Seto"],
    creator: "Gege Akutami",
    category: "action",
    isOriginal: false,
    tmdbId: 95479,
    youtubeTrailerId: "pkZXBNda8kM"
  },
  {
    id: "the-boys",
    title: "The Boys",
    type: "TV Series",
    overview: "A ragtag squad of vigilantes known as 'The Boys' embark on a bloody quest to take down the corrupt, celebrity superheroes managed by the sinister conglomerate Vought.",
    backdrop: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    poster: "https://image.tmdb.org/t/p/w780/7R6rU3mK5F9s8m7y6d5e4w3q2.jpg",
    matchScore: 98,
    year: "2024",
    ageRating: "A 18+",
    duration: "4 Seasons",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Action", "Dark Satire", "Superhero Drama"],
    cast: ["Karl Urban", "Jack Quaid", "Antony Starr", "Erin Moriarty"],
    creator: "Eric Kripke",
    category: "action",
    isOriginal: false,
    tmdbId: 76479,
    youtubeTrailerId: "06rueu_fh30"
  },
  {
    id: "black-mirror",
    title: "Black Mirror",
    type: "TV Series",
    overview: "A mind-bending sci-fi anthology series exploring humanity's greatest technological innovations and darkest impulses across unsettling dystopian scenarios.",
    backdrop: "https://image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    poster: "https://image.tmdb.org/t/p/w780/seCzcbAzyoIsf429994c6.jpg",
    matchScore: 97,
    year: "2023",
    ageRating: "A 18+",
    duration: "6 Seasons",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Sci-Fi", "Dystopian Anthology", "Psychological Suspense"],
    cast: ["Daniel Kaluuya", "Jon Hamm", "Bryce Dallas Howard", "Aaron Paul"],
    creator: "Charlie Brooker",
    category: "scifi",
    isOriginal: true,
    tmdbId: 42009,
    youtubeTrailerId: "V0Uv6k6p1wE"
  },
  {
    id: "dunki",
    title: "Dunki",
    type: "Movie",
    overview: "Four close friends in rural Punjab venture on an arduous backdoor donkey flight journey across borders to reach London, guided by an ex-soldier seeking to fulfill a promise.",
    backdrop: "https://image.tmdb.org/t/p/w1280/jXJxMcVoTTg5upA505z2U29rUIn.jpg",
    poster: "https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    matchScore: 95,
    year: "2023",
    ageRating: "U/A 13+",
    duration: "2h 41m",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Comedy", "Social Drama", "Emotional Journey"],
    cast: ["Shah Rukh Khan", "Taapsee Pannu", "Vicky Kaushal", "Boman Irani"],
    creator: "Rajkumar Hirani",
    category: "drama",
    isOriginal: false,
    tmdbId: 1071489,
    youtubeTrailerId: "2U8GgL9x8qA"
  }
];

// Merge without duplicate IDs
const existingIds = new Set(existingMovies.map(m => m.id));
const combined = [...existingMovies];

for (const m of newMovies) {
  if (!existingIds.has(m.id)) {
    combined.push(m);
    existingIds.add(m.id);
  }
}

// Assign clean Top 10 ranks to the first 10
combined.forEach((m, idx) => {
  if (idx < 10) {
    m.top10Rank = idx + 1;
  }
});

const content = `// Official Netflix Curated Catalog with 50 Verified HD Titles & NetMirror Streams
const movies = ${JSON.stringify(combined, null, 2)};

module.exports = movies;
`;

fs.writeFileSync(path.join(__dirname, '../src/movies.js'), content, 'utf8');
console.log('Successfully expanded movies.js to ' + combined.length + ' verified movies & TV series!');
