// Curated Netflix Movie & TV Show Catalog with High-Res Assets & Video Clips
const movies = [
  {
    id: "stranger-things",
    title: "Stranger Things",
    type: "TV Series",
    overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    backdrop: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?auto=format&fit=crop&w=600&q=80",
    matchScore: 99,
    ageRating: "U/A 16+",
    duration: "4 Seasons",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Sci-Fi", "Horror", "Nostalgic", "Teen Mystery"],
    cast: ["Winona Ryder", "David Harbour", "Millie Bobby Brown", "Finn Wolfhard"],
    creator: "The Duffer Brothers",
    category: "trending",
    isOriginal: true,
    top10Rank: 1,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  },
  {
    id: "cyberpunk-edgerunners",
    title: "Cyberpunk: Edgerunners",
    type: "TV Series",
    overview: "A street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner.",
    backdrop: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80",
    matchScore: 98,
    ageRating: "18+",
    duration: "1 Season",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Anime", "Action", "Cyberpunk", "Sci-Fi"],
    cast: ["KENN", "Aoi Yuuki", "Hiroki Touchi"],
    creator: "Studio Trigger",
    category: "trending",
    isOriginal: true,
    top10Rank: 2,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
  },
  {
    id: "interstellar",
    title: "Interstellar",
    type: "Movie",
    overview: "With humanity on the brink of extinction, a group of astronauts travels through a wormhole near Saturn in search of a new habitable world.",
    backdrop: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80",
    matchScore: 97,
    ageRating: "U/A 13+",
    duration: "2h 49m",
    quality: "4K Ultra HD",
    audio: "IMAX Enhanced",
    genres: ["Sci-Fi", "Drama", "Mind-Bending", "Space"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    creator: "Christopher Nolan",
    category: "scifi",
    top10Rank: 3,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: "squid-game",
    title: "Squid Game",
    type: "TV Series",
    overview: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    backdrop: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    matchScore: 99,
    ageRating: "18+",
    duration: "2 Seasons",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Thriller", "Suspense", "Dystopian", "Korean Drama"],
    cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-joon"],
    creator: "Hwang Dong-hyuk",
    category: "trending",
    isOriginal: true,
    top10Rank: 4,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
  },
  {
    id: "inception",
    title: "Inception",
    type: "Movie",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    backdrop: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80",
    matchScore: 96,
    ageRating: "U/A 16+",
    duration: "2h 28m",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Action", "Sci-Fi", "Heist", "Psychological Thriller"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    creator: "Christopher Nolan",
    category: "scifi",
    top10Rank: 5,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
  },
  {
    id: "wednesday",
    title: "Wednesday",
    type: "TV Series",
    overview: "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.",
    backdrop: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&w=600&q=80",
    matchScore: 98,
    ageRating: "U/A 13+",
    duration: "1 Season",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Fantasy", "Comedy", "Dark Comedy", "Mystery"],
    cast: ["Jenna Ortega", "Gwendoline Christie", "Riki Lindhome"],
    creator: "Alfred Gough, Miles Millar",
    category: "trending",
    isOriginal: true,
    top10Rank: 6,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  },
  {
    id: "dark-knight",
    title: "The Dark Knight",
    type: "Movie",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    backdrop: "https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    matchScore: 99,
    ageRating: "U/A 16+",
    duration: "2h 32m",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Action", "Crime", "Superhero", "Drama"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    creator: "Christopher Nolan",
    category: "action",
    top10Rank: 7,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: "breaking-bad",
    title: "Breaking Bad",
    type: "TV Series",
    overview: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
    backdrop: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
    matchScore: 99,
    ageRating: "18+",
    duration: "5 Seasons",
    quality: "4K Ultra HD",
    audio: "5.1 Surround",
    genres: ["Crime", "Drama", "Suspense", "Gritty"],
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
    creator: "Vince Gilligan",
    category: "drama",
    top10Rank: 8,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
  },
  {
    id: "peaky-blinders",
    title: "Peaky Blinders",
    type: "TV Series",
    overview: "A notorious gang in 1919 Birmingham, England, is led by the fierce Tommy Shelby, a crime boss set on moving up in the world no matter the cost.",
    backdrop: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?auto=format&fit=crop&w=600&q=80",
    matchScore: 97,
    ageRating: "18+",
    duration: "6 Seasons",
    quality: "HD",
    audio: "5.1 Surround",
    genres: ["Period Piece", "Crime", "Drama", "Gritty"],
    cast: ["Cillian Murphy", "Paul Anderson", "Helen McCrory"],
    creator: "Steven Knight",
    category: "drama",
    top10Rank: 9,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
  },
  {
    id: "money-heist",
    title: "Money Heist",
    type: "TV Series",
    overview: "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.",
    backdrop: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
    matchScore: 96,
    ageRating: "18+",
    duration: "5 Parts",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Heist", "Thriller", "Action", "Spanish Drama"],
    cast: ["Úrsula Corberó", "Álvaro Morte", "Itziar Ituño"],
    creator: "Álex Pina",
    category: "action",
    isOriginal: true,
    top10Rank: 10,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: "arcane",
    title: "Arcane",
    type: "TV Series",
    overview: "Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.",
    backdrop: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?auto=format&fit=crop&w=600&q=80",
    matchScore: 99,
    ageRating: "16+",
    duration: "2 Seasons",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Animation", "Steampunk", "Action", "Sci-Fi"],
    cast: ["Hailee Steinfeld", "Ella Purnell", "Kevin Alejandro"],
    creator: "Christian Linke, Alex Yee",
    category: "trending",
    isOriginal: true,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  },
  {
    id: "the-witcher",
    title: "The Witcher",
    type: "TV Series",
    overview: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    backdrop: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    matchScore: 94,
    ageRating: "18+",
    duration: "3 Seasons",
    quality: "4K Ultra HD",
    audio: "Dolby Atmos",
    genres: ["Dark Fantasy", "Action", "Adventure", "Magic"],
    cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"],
    creator: "Lauren Schmidt Hissrich",
    category: "action",
    isOriginal: true,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
  }
];

module.exports = movies;
